//	Copyright 2019 IBM Corporation and others.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
//
:page-layout: guide
:projectid: collection-microprofile
:page-duration: 20 minutes
:page-releasedate: 2019-09-13
:page-description: Learn how to create, run, update, deploy, and deliver a simple cloud native application using the Eclipse MicroProfile Kabanero Collection
:guide-author: Kabanero
:page-tags: ['Collection', 'MicroProfile', 'Eclipse']
:page-guide-category: collections
:page-essential: true
:page-essential-order: 1
:page-permalink: /guides/collection-microprofile/
:imagesdir: /resources
= Developing cloud native microservice applications with the Java MicroProfile Kabanero Collections and Eclipse IDE

[.hidden]
NOTE: This repository contains the guide documentation source. To view
the guide in published form, view it on the https://kabanero.io/guides/{projectid}.html[website].

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you will learn

You will learn how to build a simple containerized microservice application from a Kabanero Java MicroProfile
Collection in your Eclipse IDE.

The Kabanero Collection you will use for this example is `java-microprofile` . There is another Java Collection called `java-sprint-boot2` but this example is going to focus on MicroProfile.

// =================================================================================================
// Prerequisites
// =================================================================================================

== Prerequisites

. You must have https://docs.docker.com/get-started/[Docker] installed.
. You must install the Eclipse Codewind Extension from the https://marketplace.eclipse.org/content/codewind[Eclipse Marketplace], which creates a *CODEWIND* workspace and downloads Docker images to your Docker registry
. (Optional) If you have an enterprise-specific Kabanero Collection Hub,
you need the URL to your index file.

Everything is now set up, and you're ready to create your first project!

// =================================================================================================
// Getting started
// =================================================================================================

== Getting started

Kabanero brings together open source technologies that provide a framework for developing cloud native microservice
applications. As a developer, you are likely to have a preferred IDE for writing application
code. In this guide, we will show you how you can develop a simple containerized microservice application that is
based on the Java MicroProfile Kabanero Collection in the Eclipse IDE.

Kabanero contains Appsody, which is designed to enable applications to be built and tested inside a Docker container.
To access Appsody functions from your IDE, you need Eclipse Codewind, which provides a rich user interface that integrates
seamlessly into VS Code. Codewind also provides performance and monitoring tools to help you test and debug applications
in containers.

When you install Eclipse Codewind, an extension to Appsody is automatically installed as part of your
Codewind workspace. By default, Codewind is configured to use the latest Appsody stacks that are
available in the Appsody GitHub repository. However, those stacks are not integrated with Kabanero.
In order to use Appsody with Kabanero you need to configure Codewind to use a Kabanero Collection Hub.

== Configuring your environment to use a Kabanero Collection Hub

As a developer, your enterprise architect might provide you with the URL of a Kabanero Collection Hub that your
organisation has defined for developers to use. If not, you should clone the *public* Kabanero Collection
Hub locally. The public collection is updated on a regular basis, so by making a copy, you avoid adopting unplanned changes.

To keep things simple in this guide you will add the latest *public* Kabanero Collection Hub repository instead of a clone of
a Kabanero Collection Hub repository.

To edit the Template Sources, the places Codewind looks for Collections from, right-click the Projects (Local) section of the Codewind Explorer and select `Manage Template Sources`. If you cannot see the Codewind Explorer, show it by going to Window > Show View > Codewind Explorer. If Codewind Explorer is not in that list, go to Other instead and select it in the dialog box.

After the right-click, a new box appears with a list of template sources, including Standard Codewind Templates, and Appsody Stacks. Kabanero Collections may already be showing in this list. If so, enable it with the tick box. If Kabanero Collections is not in the list, select Add enter `Kabanero Collections` as a description and for the URL field, enter `https://github.com/kabanero-io/collections/releases/latest/download/kabanero-index.json`.

Disable Appsody Stacks by deselecting the tick box next to it, if both Kabanero Collections and Appsody Stacks are enabled at the same time, you will get two versions of some products, one found in Kabanero and one in Appsody.

Codewind is now configured to use the *public* Kabanero Collection Hub.

== Initializing your project

Find the **Projects (Local)** row inside the Codewind Explorer, which should be showing No Projects, and right-click and press Create New Project to get a list of available Templates and Collections.

// Window showing Eclipse with the Codewind Explorer right clicked.
image:rightclick-project[Diagram
shows popup to create a new Project]


In this guide, we are going to create a `java-microprofile` microservice application.

From the **Create a new project** window, choose the *Kabanero Eclipse MicroProfile Template*, as shown in the following diagram:

// Window showing the picking of a Kabanero Collection from the New Project list.
image:create-project[Diagram
shows popup to create a new Project]

Choose a suitable name for your project and select *Finish* to save it.

Your new project is created, built, and is compiling inside an Appsody Docker container. To see the status of the build, right-click the project in Codewind Explorer, select Show Log Files and chose **Appsody.log**. This will open the logs for the Docker container in a Console Window inside Eclipse.

Once is has compiled and is running on localhost, the status will change from **[Stopped] [Build Successful]** to **[Running] [Build Successful]**. Right-click the Project in Codewind Explorer and select Open Application to view the app running on your local machine! 

// Image showing the open Application option.
image:open-application[Diagram
shows the open application option]

== Understanding the project layout

Projects are created with a default set of files, which you can find in a Project Explorer in your *CODEWIND-WORKSPACE*. 

If you have created a New Project and aren't seeing in in the Project Explorer, Eclipse may be pointing at the wrong workspace. To fix this, go to `File > Switch Workspace > Other` and navigate to `codewind-workspace`.

// Showing project layout inside the project explorer pane.
image:project-explorer[Diagram
shows the Project Explorer view]

Open the Application by right-clicking the Project from the Codewind Explorer and selecting **Open Application**. 

The Eclipse browser opens to display "Welcome to your Appsody Microservice" on `http://127.0.0.1:<local_port_number>/`. Make a note
of the <local_port_number> for your next task.

== Creating and updating the application

You are now going to create a new route that listens on `http://127.0.0.1:<local_port_number>/starter/hello`.

In Project Explorer, right click on the dev.appsody.starter package located inside the Java Resources > src/main/java folder and create a new file called `HelloResource`. Ensure you are using the Java Resources folder and not the raw path located beneath this section.

Add the following code to this new file:

```
package dev.appsody.starter;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;


@Path("/")
public class HelloResource {
    @GET
    @Path("hello")
    @Produces(MediaType.TEXT_PLAIN)
    public String helloWorld() {
        return "Hello World!";
    }
}
```

Save the changes.

Codewind watches for file changes and automatically recompiles your application. Point your browser to
`http://127.0.0.1:<local_port_number>/starter/hello` to see your new route, which displays **Hello World!**.

This code is creating a new path on **/hello** to return a String to the browser saying `Hello World!`. The starter part of the full URL comes from the `StarterApplication.java` file which defines the routes as all beginning with **/starter**.

== Testing and debugging the application

You can perform a number of operations through the Eclipse Codewind Explorer interface
that help you develop, test, and debug your application. Right-click on your project to see a
list of available tasks:

// Meny list of available options on project
image:rightclick-options[Diagram
shows the right click options]

- you can disable the automated build of your project and build it on demand
- you can restart your application in run mode or debug mode
- you can view the available logs to troubleshoot issues
- you can find information about the running app by opening the Project
Overview. Eclipse displays information about your project, including the location, status, and any ports in use. The output is similar to the
following screenshot:

// Screenshot of overview page
image:project-overview[Diagram
shows the Project Overview page]

- you can stop the application, by clicking the *Disable project* button.

At some stage in development, you might want to do some local
performance testing. As well as checking whether your code runs cleanly, Codewind
provides application metrics and performance monitoring. For more information about
developing applications with Eclipse Codewind, see the
https://www.eclipse.org/codewind/mdteclipsegettingstarted.html[Codewind
documentation].

Congratulations! You have now learned the basic steps for developing a microservice
application in Eclipse that's based on the Java MicroProfile Kabanero Collection.


// =================================================================================================
// Delivering your application
// =================================================================================================

== Delivering your application

When you've finished developing and testing your microservice application on your local system, the
next stage in the process is to test the application on a kubernetes or Knative environment. Your
role in the overall process might end by delivering your changes to a GitHub repository. Here, your
operations team can automate the deployment of your microservice application to kubernetes or Knative by implementing
Tekton webhooks that trigger Tekton pipelines.

Want to learn about Tekton? Using Tekton pipelines to deploy microservice applications is covered
in different guide.